spring:
  application:
    name: herlandio7-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #habilita localizar serviço
          lower-case-service-id: true #localiza se estiver caixa baixa
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}
          
server:
  port: 8080

eureka:
  client:
    fetch-registry: true #busca registro
    register-with-eureka: true #registra com eureka
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_SERVER}:${EUREKA_PORT}/eureka #rota do eureka