spring:
  application:
    name: herlandio7-client-service
server:
  port: 0 #sobe em porta aleatoria
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_SERVER}:${EUREKA_PORT}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} #gera um nome especifico no eureka
management: # expondo todos os endpoints do actuator
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: ./logs/logs-file.log