spring:
  application:
    name: herlandio7-credit-assessor-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: guest
    password: guest
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://eureka-user:123@${EUREKA_SERVER}:8761/eureka #o começo tem o login do eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} #gera um nome especifico no eureka
mq:
  queues:
    issuing-cards: issuing-cards
    
management: # expondo todos os endpoints do actuator
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: ./logs/logs-file.log