spring:
  application:
    name: herlandio7-credit-assessor-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_SERVER}:${EUREKA_PORT}/eureka #o começo tem o login do eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} #gera um nome especifico no eureka
mq:
  queues:
    issuing-cards: issuing-cards
    
management: # expondo todos os endpoints do actuator
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: ./logs/logs-file.log